on: [push, pull_request]

name: Continuous integration

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - rust: stable
                      env:
                          RUSTFMTCHK: true
                    - rust: nightly
                      env:
                          RUSTFMTCHK: false
                    - rust: 1.48.0
                      env:
                          RUSTFMTCHK: false
        steps:
            - name: Checkout Crate
              uses: actions/checkout@v2
            - name: Checkout Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true
            - name: Running test script
              env: ${{ matrix.env }}
              run: ./contrib/test.sh

    integrations-tests:
        name: Integration Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rust: [stable]
                bitcoinversion:
                    [
                        "25.1.0",
                    ]
        steps:
            - name: Checkout Crate
              uses: actions/checkout@v2
            - name: Checkout Toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust }}
                  override: true
            - name: Running test script
              env:
                  BITCOINVERSION: ${{ matrix.bitcoinversion }}
              run: ./contrib/test.sh
